version: '2'

services:
  web:
    image: my-shuttle/web
    build:
      context: .
      dockerfile: ./src/Dockerfile
    depends_on:
      - db
    ports: 
      - "8081:8080"
  db:
    image: my-shuttle/db
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - "3306"
