version: '2'

services:
  web:
    image: my-shuttle/web
    depends_on:
      - db
    ports: 
      - "80:8080"
  db:
    image: my-shuttle/db
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - "3306"
